const data = [
  {
    id: 1,
    name: "John",
    born: "1990",
    gender: "male",
    live: "USA",
    hobby: "coding",
    email: "johndoe@me.com",
  },
  {
    id: 2,
    name: "Jane",
    born: "1999",
    gender: "female",
    live: "England",
    hobby: "Basketball",
    email: "Jane@me.com",
  },
  {
    id: 3,
    name: "Jim",
    born: "1995",
    gender: "male",
    live: "Canada",
    hobby: "watch movie",
    email: "Jim@me.com",
  },
  {
    id: 4,
    name: "Jill",
    born: "1993",
    gender: "female",
    live: "Mexico",
    hobby: "swimming",
    email: "Jill@me.com",
  },
  {
    id: 5,
    name: "Jack",
    born: "1991",
    gender: "male",
    live: "USA",
    hobby: "soccer",
    email: "Jack@me.com",
  },
  {
    id: 6,
    name: "Jenny",
    born: "1996",
    gender: "female",
    live: "France",
    hobby: "music",
    email: "Jenny@me.com",
  },
  {
    id: 7,
    name: "Alice",
    born: "1992",
    gender: "female",
    live: "Australia",
    hobby: "reading",
    email: "Alice@me.com",
  },
  {
    id: 8,
    name: "Bob",
    born: "1988",
    gender: "male",
    live: "New Zealand",
    hobby: "hiking",
    email: "Bob@me.com",
  },
  {
    id: 9,
    name: "Charlie",
    born: "1990",
    gender: "male",
    live: "Ireland",
    hobby: "surfing",
    email: "Charlie@me.com",
  },
  {
    id: 10,
    name: "Diana",
    born: "1994",
    gender: "female",
    live: "South Africa",
    hobby: "painting",
    email: "Diana@me.com",
  },
];

export default data;
